[project]
name = "ragent"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.0.12",
    "google-adk>=1.2.1",
    "litellm>=1.72.2",
    "pypdf2>=3.0.1",
    "sentence-transformers>=4.1.0",
]
